### ISSUE TITLE
Icon/Logo Proposal

### ISSUE THREAD

**Issue by loydjayme25** [profchydon/steemask#1]
can i submit my designs for your project ?

**Comment by profchydon** [comment]
Sure you can. Let me know when you submit it.

**Comment by loydjayme25** [comment]
What is your preferred sizes in px sir ? So that i may able to adjust my designs

**Comment by loydjayme25** [comment]
**SAMPLES**

**For ICON and LOGO**

![proposal](https://user-images.githubusercontent.com/37318022/38863879-8e8357c2-426b-11e8-97a6-5e98e2f64fc2.png)

**For WALLPAPER**

![wallpaper](https://user-images.githubusercontent.com/37318022/38863897-a2d5d7f4-426b-11e8-9dcd-2065e9051547.png)

**Comment by profchydon** [comment]
You have to submit it on utopian as a post.

**Comment by loydjayme25** [comment]
before submitting it sir, project owner must use my design so that they will approve it..

**Comment by princekelly1** [comment]
i must sav i love the design you made, would suggest you add a steem logo to it in a creative way. my opinion

**Comment by loydjayme25** [comment]
thank you sir, i will add some changes and also the steem logo
